set working-directory := "../.."

# View help text
@help *args:
    .environments/documentation/scripts/help.nu {{ args }}

# Open a pre-configured development environment
@develop *args:
    .environments/documentation/scripts/develop.nu {{ args }}

alias dev := develop

# Serve documentation files and recompile on changes
@serve *args:
    .environments/documentation/scripts/serve.nu {{ args }}

# Open the documentation page
@open *args:
    .environments/documentation/scripts/open-documentation.nu {{ args }}
